# Generated by Django 4.2.17 on 2025-01-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='carbs/100'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='fat/100'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kcal',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='kcal/100'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='protein/100'),
        ),
    ]
