# Generated by Django 4.2.17 on 2025-02-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='kcal/100g')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='protein/100g')),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='fat/100g')),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='carbs/100g')),
            ],
        ),
    ]
