# Generated by Django 4.2.17 on 2025-02-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.AddField(
            model_name='meal',
            name='available_portions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='total_portions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
