# Generated by Django 4.2.17 on 2025-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
