# Generated by Django 4.2.17 on 2025-04-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mealentry_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealentry',
            name='created_at',
        ),
    ]
