# Generated by Django 4.2.17 on 2025-03-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mealentry_options_meal_infinite_portions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealentry',
            name='portions',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
