# Generated by Django 4.2.17 on 2025-03-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mealentry_portions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='available_portions',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_portions',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
