# Generated by Django 4.2.17 on 2025-05-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_meal_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='grams',
            field=models.DecimalField(decimal_places=2, default=2012, max_digits=6, verbose_name='grams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
