# Generated by Django 4.2.17 on 2025-05-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mealentry_grams_mealentry_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealentry',
            name='grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='grams'),
        ),
    ]
