# Generated by Django 4.2.17 on 2025-02-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
